<?php 
    // verifica se o usuário está logado, se não, redireciona para a tela de login
	include_once "../backEnd/valida_usuario.php";

    if ( isset($_POST) && ( isset($_POST['email']) && isset($_POST['senha'])) ) {
        $email = $_POST['email'];
        $senha = $_POST['senha'];
        
        if ( ! validaLogin($email,$senha) ) {
            header("location: login.html");
        }
    }
    else {
        if ( ! Logado() ){
            header("location: login.html");
        }
    }
?>
<html>
<head>
    <meta charset="utf-8">
    <link href="assets/css/moltran.min.css" rel="stylesheet" type="text/css">
</head>
    <body>
        <div id="wrapper">        
        <div class="topbar">
            <div class="topbar-left">
                <div class="text-center"><a href="index.php" class="logo"><img src="assets/images/logo-appriori.png" class="img-responsive" /></a></div>
            </div>
            <div class="navbar navbar-default container" role="navigation">
                <br/>
                <ul class="nav navbar-nav navbar-right pull-right container">                           
                    <li class="hidden-xs">
                        <div class="col-md-12">                                    
                            <label class="text-right"><?php echo "Nome:  " . $_SESSION["nome"] . "  "; ?></label>                                
                        </div>
                    </li>

                    <li class="hidden-xs">                                    
                        <form class="" action="../backEnd/logout.php">
                            <button class="btn btn-danger" type="submit"><i class="md md-settings-power"></i> Sair</button>
                        </form>  
                    </li>
                </ul>
            </div>
        </div>
        <div class="left side-menu">
            <div class="sidebar-inner">
                
                <div id="sidebar-menu">
                    <ul>
<!--                        <li><a href="index.php" class="waves-effect waves-light"><i class="md md-home"></i><span>Home</span></a></li>-->
                        <li class="active-menu"><a type="text" class="waves-light active">Cadastros</a>
                                <li><a class="waves-effect waves-light" id="equipamentos" href="equipamentos.php">Equipamento</a></li>
                                <li><a class="waves-effect waves-light" id="funcionarios" href="funcionarios.php">Funcionário</a></li>
                                <li><a class="waves-effect waves-light" id="locais" href="locais.php">Local</a></li>
                        </li>
                        <li class="active-menu"><a type="text" class="waves-light active">Listagem Chamados</a>
                                <li><a class="waves-effect waves-light" id="chamadosAbertos" href="chamadosAbertos.php">Abertos</a></li>
                                <li><a class="waves-effect waves-light" id="chamadosFechados" href="chamadosFechados.php">Fechados</a></li>
                        </li>
                    </ul>                    
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="content-page">
            <div class="content">
                <div class="container" id="conteudo">
    <script>
        var resizefunc = [];
    </script>
</body>
</html>